var TeamImages = {
	"49ers": require('image!49ers'),
	"Bengals": require('image!Bengals'),
	"Bills": require('image!Bills'),
	"Broncos": require('image!Broncos'),
	"Buccaneers": require('image!Buccaneers'),
	"Cardinals": require('image!Cardinals'),
	"Chargers": require('image!Chargers'),
	"Chicago": require('image!Chicago'),
	"Chiefs": require('image!Chiefs'),
	"Colts": require('image!Colts'),
	"Cowboys": require('image!Cowboys'),
	"Dolphins": require('image!Dolphins'),
	"Eagles": require('image!Eagles'),
	"Falcons": require('image!Falcons'),
	"Giants": require('image!Giants'),
	"Jaguars": require('image!Jaguars'),
	"Jets": require('image!Jets'),
	"Lions": require('image!Lions'),
	"Packers": require('image!Packers'),
	"Panthers": require('image!Panthers'),
	"Patriots": require('image!Patriots'),
	"Raiders": require('image!Raiders'),
	"Rams": require('image!Rams'),
	"Ravens": require('image!Ravens'),
	"Redskins": require('image!Redskins'),
	"Saints": require('image!Saints'),
	"Seahawks": require('image!Seahawks'),
	"Steelers": require('image!Steelers'),
	"Texans": require('image!Texans'),
	"Titans": require('image!Titans'),
	"Vikings": require('image!Vikings'),
	"Browns": require('image!Browns'),
	"Baltimore": require('image!Baltimore'),
}
module.exports = TeamImages;